#!/usr/bin/env node
'use strict';

/**
 * Headless trainer: runs the exact same engine as the browser (no DOM needed)
 * at full CPU speed and writes the best brains to js/data/pretrained.js.
 *
 *   node tools/train.js                         # all presets, defaults
 *   node tools/train.js --preset circuit --generations 80 --population 200
 */
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = path.resolve(__dirname, '..');
const ENGINE = [
  'js/core/math.js',
  'js/core/geometry.js',
  'js/core/spatial-grid.js',
  'js/core/graph.js',
  'js/core/theme.js',
  'js/world/items.js',
  'js/world/world.js',
  'js/world/presets.js',
  'js/ai/network.js',
  'js/ai/evolution.js',
  'js/sim/sensor.js',
  'js/sim/car.js',
  'js/sim/traffic.js',
  'js/sim/simulation.js',
];

function loadEngine() {
  const source = ENGINE.map((f) => fs.readFileSync(path.join(ROOT, f), 'utf8').replace(/^'use strict';/m, '')).join('\n;\n');
  vm.runInThisContext(
    `'use strict';\n${source}\n;globalThis.ND = { World, Presets, Simulation, NeuralNetwork, Car };`,
    { filename: 'neurodrive-engine.js' },
  );
  return globalThis.ND;
}

function parseArgs(argv) {
  const args = { preset: 'all', generations: 60, population: 200, traffic: 6, out: 'js/data/pretrained.js', varyTraffic: true };
  for (let i = 2; i < argv.length; i++) {
    const key = argv[i].replace(/^--/, '');
    const val = argv[i + 1];
    if (key === 'fixed-traffic') { args.varyTraffic = false; continue; }
    if (['generations', 'population', 'traffic'].includes(key)) args[key] = Number(val);
    else args[key] = val;
    i++;
  }
  return args;
}

function train(ND, presetId, opts) {
  const data = ND.Presets.get(presetId).build();
  const world = ND.World.fromJSON(data).generate({ detail: false });
  const sim = new ND.Simulation(world, {
    population: opts.population,
    trafficCount: opts.traffic,
    varyTraffic: opts.varyTraffic,
    generationTime: 45,
  });
  const dt = 1 / 60;
  const t0 = Date.now();
  console.log(`\n▶ ${data.name}: ${world.checkpoints.length} checkpoints, ${world.roadBorders.length} border segments`);
  sim.onGeneration = (s) => {
    const bar = '█'.repeat(Math.round(s.coverage * 30)).padEnd(30, '·');
    console.log(
      `  gen ${String(s.generation).padStart(3)}  best ${s.best.toFixed(1).padStart(7)}  avg ${s.avg.toFixed(1).padStart(6)}  ` +
      `coverage ${bar} ${(s.coverage * 100).toFixed(0).padStart(3)}%${s.record ? '  ★' : ''}`,
    );
  };
  while (sim.evolution.generation <= opts.generations) sim.step(dt);
  const secs = ((Date.now() - t0) / 1000).toFixed(1);
  console.log(`  done in ${secs}s — best fitness ${sim.evolution.bestEverFitness.toFixed(1)} (gen ${sim.evolution.bestEverGeneration})`);
  return { brain: sim.evolution.bestEver.toJSON(), fitness: sim.evolution.bestEverFitness, generations: opts.generations };
}

function main() {
  const opts = parseArgs(process.argv);
  const ND = loadEngine();
  const ids = opts.preset === 'all' ? ND.Presets.list.filter((p) => p.id !== 'blank').map((p) => p.id) : [opts.preset];

  const outFile = path.join(ROOT, opts.out);
  let existing = {};
  if (fs.existsSync(outFile)) {
    const m = fs.readFileSync(outFile, 'utf8').match(/=\s*(\{[\s\S]*\});/);
    if (m) existing = JSON.parse(m[1]);
  }
  for (const id of ids) existing[id] = train(ND, id, opts);

  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(
    outFile,
    `'use strict';\n// Generated by tools/train.js on ${new Date().toISOString().slice(0, 10)} — do not edit by hand.\n` +
      `const PRETRAINED_BRAINS = ${JSON.stringify(existing)};\n`,
  );
  console.log(`\n✔ wrote ${path.relative(ROOT, outFile)}`);
}

if (require.main === module) main();
module.exports = { loadEngine };
